--------------------------------------------------------
--  File created - ÇÑ¹¾ÄËÑÊº´Õ-¸Ñ¹ÇÒ¤Á-17-2558   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table CPE_ORDER
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."CPE_ORDER" 
   (	"C_USERNAME" VARCHAR2(20 BYTE), 
	"C_PRODUCT" VARCHAR2(50 BYTE), 
	"C_PRICE" NUMBER, 
	"C_PATH" VARCHAR2(50 BYTE), 
	"C_ID" NUMBER, 
	"PRODUCT_ID" NUMBER
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into SYSTEM.CPE_ORDER
SET DEFINE OFF;
Insert into SYSTEM.CPE_ORDER (C_USERNAME,C_PRODUCT,C_PRICE,C_PATH,C_ID,PRODUCT_ID) values ('tick','acer',324434,'image\pc\pacer-01.jpg',1,2);
Insert into SYSTEM.CPE_ORDER (C_USERNAME,C_PRODUCT,C_PRICE,C_PATH,C_ID,PRODUCT_ID) values ('tick','acer',30000,'image\pc\pacer-02.jpg',2,1);
Insert into SYSTEM.CPE_ORDER (C_USERNAME,C_PRODUCT,C_PRICE,C_PATH,C_ID,PRODUCT_ID) values ('tick','acer',22000,'image\pc\pacer-05.jpg',3,76);
Insert into SYSTEM.CPE_ORDER (C_USERNAME,C_PRODUCT,C_PRICE,C_PATH,C_ID,PRODUCT_ID) values (null,'samsung',45633,'image\phone\psamsung-02.jpg',4,51);
Insert into SYSTEM.CPE_ORDER (C_USERNAME,C_PRODUCT,C_PRICE,C_PATH,C_ID,PRODUCT_ID) values ('sawanya','samsung',50000,'image\pc\psamsung-01.jpg',5,77);
--------------------------------------------------------
--  DDL for Index CPE_ORDER_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."CPE_ORDER_PK" ON "SYSTEM"."CPE_ORDER" ("C_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 167 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table CPE_ORDER
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."CPE_ORDER" ADD CONSTRAINT "CPE_ORDER_PK" PRIMARY KEY ("C_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 167 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "SYSTEM"."CPE_ORDER" MODIFY ("C_ID" NOT NULL ENABLE);
