--------------------------------------------------------
--  File created - ÇÑ¹¾ÄËÑÊº´Õ-¸Ñ¹ÇÒ¤Á-17-2558   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table AUSER
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."AUSER" 
   (	"NAME" VARCHAR2(20 BYTE), 
	"BIRTHDAY" VARCHAR2(20 BYTE), 
	"ADDRESS" VARCHAR2(59 BYTE), 
	"EMAIL" VARCHAR2(20 BYTE), 
	"TEL" NUMBER, 
	"USERNAME" VARCHAR2(20 BYTE), 
	"PASS" VARCHAR2(20 BYTE), 
	"STATUS" VARCHAR2(20 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into SYSTEM.AUSER
SET DEFINE OFF;
Insert into SYSTEM.AUSER (NAME,BIRTHDAY,ADDRESS,EMAIL,TEL,USERNAME,PASS,STATUS) values ('Narumon','2015-12-01','Chiang rai','narumonk@outlook.com',883457212,'tick','111',null);
Insert into SYSTEM.AUSER (NAME,BIRTHDAY,ADDRESS,EMAIL,TEL,USERNAME,PASS,STATUS) values ('Sawan','2015-12-17','Chiang mai','Sawanya@345',88934576,'sawanya','1234',null);
Insert into SYSTEM.AUSER (NAME,BIRTHDAY,ADDRESS,EMAIL,TEL,USERNAME,PASS,STATUS) values ('Putisan','2015-12-16','Lamphun','tick@hotmail.com',53665242,'Gotgi','222','admin');
--------------------------------------------------------
--  DDL for Index AUSER_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."AUSER_PK" ON "SYSTEM"."AUSER" ("USERNAME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table AUSER
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."AUSER" ADD CONSTRAINT "AUSER_PK" PRIMARY KEY ("USERNAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "SYSTEM"."AUSER" MODIFY ("USERNAME" NOT NULL ENABLE);
